-- CreateTable
CREATE TABLE `UserInfo` (
    `id` VARCHAR(191) NOT NULL,
    `visa_to_country` VARCHAR(191) NULL,
    `name` VARCHAR(191) NULL,
    `name_alias` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `gender` ENUM('Male', 'Female', 'Other') NULL,
    `dob` DATETIME(3) NULL,
    `pob` TEXT NULL,
    `marital_status` VARCHAR(191) NULL,
    `husband_wife_pob` VARCHAR(191) NULL,
    `is_has_kid` BOOLEAN NULL,
    `country` VARCHAR(191) NULL,
    `nationality` VARCHAR(191) NULL,
    `other_nationality` VARCHAR(191) NULL,
    `address_on_paper` VARCHAR(191) NULL,
    `current_address` VARCHAR(191) NULL,
    `phone_number` VARCHAR(191) NULL,
    `id_issue_date` DATETIME(3) NULL,
    `id_expire_date` DATETIME(3) NULL,
    `id_country_receive` VARCHAR(191) NULL,
    `id_city_receive` VARCHAR(191) NULL,
    `id_lost_reason` VARCHAR(191) NULL,
    `current_job` VARCHAR(191) NULL,
    `current_job_address` VARCHAR(191) NULL,
    `current_job_start_date` DATETIME(3) NULL,
    `current_company_phone_number` VARCHAR(191) NULL,
    `current_job_title` VARCHAR(191) NULL,
    `current_job_salary` INTEGER NULL,
    `current_job_detail` TEXT NULL,
    `old_job` VARCHAR(191) NULL,
    `old_job_title` VARCHAR(191) NULL,
    `old_job_start_date` DATETIME(3) NULL,
    `old_job_end_date` DATETIME(3) NULL,
    `education_level` VARCHAR(191) NULL,
    `school_name` VARCHAR(191) NULL,
    `major` VARCHAR(191) NULL,
    `school_start_date` DATETIME(3) NULL,
    `school_end_date` DATETIME(3) NULL,
    `is_parent_live_in_visiting_country` BOOLEAN NULL,
    `stay_status` VARCHAR(191) NULL,
    `is_relatives_living_in_visiting_country` BOOLEAN NULL,
    `relatives_info_living_in_visiting_country` TEXT NULL,
    `relationship_with_relatives` VARCHAR(191) NULL,
    `relatives_stay_status` VARCHAR(191) NULL,
    `expected_start_date` DATETIME(3) NULL,
    `accompanying_person` VARCHAR(191) NULL,
    `traveled_countries` TEXT NULL,
    `foreign_languages` TEXT NULL,
    `trip_purpose` TEXT NULL,
    `trip_payroll_person` VARCHAR(191) NULL,
    `visa_type_owned` VARCHAR(191) NULL,
    `is_lived_in_visa_coutry` BOOLEAN NULL,
    `is_lived_in_visa_coutry_date` DATETIME(3) NULL,
    `is_lived_in_visa_coutry_days_stay` INTEGER NULL,
    `is_denied_visa` BOOLEAN NULL,
    `denied_visa_reason` TEXT NULL,
    `denied_visa_number_of_time` INTEGER NULL,
    `is_had_visa_country_not_used` BOOLEAN NULL,
    `visa_country_not_used` VARCHAR(191) NULL,
    `guarantee_documents` TEXT NULL,
    `social_network` VARCHAR(191) NULL,
    `is_belong_to_some_tribe_or_party` BOOLEAN NULL,
    `party_join_date` DATETIME(3) NULL,
    `is_work_for_some_charity_organization` BOOLEAN NULL,
    `is_weapons_trained` BOOLEAN NULL,
    `is_worked_on_army` BOOLEAN NULL,
    `is_has_some_sick` BOOLEAN NULL,
    `is_had_been_arrested_by_crime` BOOLEAN NULL,
    `is_renounce_citizenship` BOOLEAN NULL,
    `is_done_filling` BOOLEAN NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ErrorLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `message` TEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
